### ISSUE TITLE
Improve CI build times, esp. on Ubuntu

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#107]
These are our current CI build times through our GitHub Action:

- Mac: 3m 9s
- Windows: 8m 22s
- Ubuntu: 13m 22s

Ubuntu is spending 8 min just installing spirv-tools, this we should fix so we at least get down to 8m total build times instead of 13 min.

Just download the spriv-tools executables directly instead of using apt? think was some discussion in chat. cc @Jake-Shadle

**Comment by Jake-Shadle** [comment]
It was originally downloading the executables directly, but was changed in #63 to use brew instead, not sure why exactly, but you can see the CI runs before that PR were around ~6m which is still fairly high, but a lot better.

**Comment by repi** [comment]
Oh, does sound like we should go back!

**Comment by khyperia** [comment]
It looks like we're building at least some crates twice from the split `cargo test`. My guess:

current ci.yaml:

```yaml
      - run: cargo test --workspace --exclude example-runner
      - if: ${{ runner.os != 'macOS' }}
        run: cargo test --workspace example-runner
```

probably better ci.yaml:

```yaml
      - if: ${{ runner.os != 'macOS' }}
        run: cargo test --workspace
      - if: ${{ runner.os == 'macOS' }}
        run: cargo test --workspace --exclude example-runner
```
