### ISSUE TITLE
spirv-builder should declare dependencies on Cargo.toml files.

### ISSUE THREAD

**Issue by eddyb** [EmbarkStudios/rust-gpu#404]
For #403 I changed the workspace `Cargo.toml`, but that didn't result in a rebuild of `sky-shader`, whereas something like this does cause a rebuild (of `example-runner-wgpu`, in this example):
```toml
[profile.dev.package."example-runner-wgpu"]
opt-level = 3
```

So I think we need `spirv-builder` to get the workspace `Cargo.toml` (and `Cargo.lock`, I suppose) paths from `Cargo` somehow, and also list those out as "rebuild if changed".
