### ISSUE TITLE
Document how to use [profile.{dev,release}.build-override] to speed up shader building.

### ISSUE THREAD

**Issue by eddyb** [EmbarkStudios/rust-gpu#448]
We merged #437 for ourselves, but we should document that users should put something like this in their workspace `Cargo.toml`:
```toml
# Compile build-dependencies in release mode with
# the same settings as regular dependencies.
[profile.release.build-override]
opt-level = 3
codegen-units = 16
```

Note that this *only* speeds up shader building for `--release` (host) builds (of e.g. `example-runner-wgpu`), if one needs debug (host) builds to quickly build shaders as well, they also need:
```toml
[profile.dev.build-override]
opt-level = 3
```

(This does imply that all of your e.g. proc macro or unrelated build script dependencies will also be optimized, which might slow down *full rebuilds* a bit, but it should overall be a speedup for *incremental rebuilds* after local changes in the workspace)

`rust-gpu-shadertoys` [does both](https://github.com/LykenSol/rust-gpu-shadertoys/blob/809ab26ae95e084488abaf87d714f389d7b65e0c/Cargo.toml#L35-L40) just because of how much code is built as one SPIR-V module (it takes 15 seconds *at best*).
